spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nelo
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

